enum UsersActions {
  SET_IS_VERIFYING_EMAIL = "SET_IS_VERIFYING_EMAIL",
  SET_IS_CHANGING_PWD = "SET_IS_CHANGING_PWD",
}

export const SET_IS_vERIFYING_EMAIL = UsersActions.SET_IS_VERIFYING_EMAIL;
export const SET_IS_CHANGING_PWD = UsersActions.SET_IS_CHANGING_PWD;
